security:
  basic:
    enabled: false

management:
  security:
    enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri}/eureka/

spring:
  cloud:
    config:
      uri: ${vcap.services.config-service.credentials.uri}
