security:
  basic:
    enabled: false

management:
  security:
    enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80

spring:
  cloud:
    config:
      uri: ${vcap.services.config-service.credentials.uri}
    services:
      registrationMethod: route
