eureka:
  instance:
    hostname: eureka-server-mj.cfapps.io
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
